### PR TITLE
Get variable values as `int`, `double` and `bool`

### PR DESCRIPTION
**Pull request by Tandashi**
Allows to get the variable values casted to the specific type. If the variable does not exist, the `fallback` is used. However, when also no `fallback` is provided, an `AssertionError` is thrown. Furthermore, a `FormatException` is thrown when the variable exists, but the value can not be casted to the specific type.

### CODE REVIEW

**Comment by java-james** [comment]
Thanks for making a PR for this feature. Have had a skim and looks good will make time for a proper look & a release if merged!

**Comment by Tandashi** [comment]
Resolved the merge conflicts :)

Any update on this? Just curious.

**Comment by java-james** [comment]
I'm sorry it's taken this long to get eyes back on this.
I will be resolving a few issues and merging a few PRs in the next couple of weeks. Let me include reviewing this.

**Comment by java-james** [comment]
Will include in next release with some docs on usage. Thanks for the feature and apologies for the time it took to get back to this one.

**Comment by Tandashi** [comment]
@java-james All good no worries. Was / am happy to contribute to this :)

**Comment by java-james** [comment]
Thanks. I'm aiming to cut the next release on this library by end of week :)

**Pull request merged**
