### PR TITLE
fix(test): make the testLoad method signature synchronous to match the body

### PR DESCRIPTION
**Pull request by safarmer**
Also added a small helper method to get non-null string values with a fallback default.

### CODE REVIEW

**Comment by ngxingyu** [comment]
- The changes for the signature is good.
- I added this test to the dotenv_test.dart file for the fallback get method, we still need to handle the 2nd case where the var is null but the fallback wasn't set, perhaps default to null or "". It might be easier to let the user handle it within the code like `dotenv['COMMENTS']??'fallback'`
```
    test('fallback getter works', () {
      expect(dotenv.get('COMMENTS', fallback: 'sample'), 'sample');
      expect(dotenv.get('COMMENTS'), null);
      expect(dotenv.get('EQUAL_SIGNS', fallback: 'sample'), 'equals==');
    });
```

**Comment by safarmer** [comment]
Thanks for the review @ngxingyu. How do you feel about the update I pushed? I went for the approach like the framework uses with Scaffold etc where they added a `maybeOf(...)` method to handle the cases where you know the value might be missing. This way users could skip some boilderplate if they know their values are set or they want to fail-fast. Thoughts?

**Comment by java-james** [comment]
@safarmer Is #43 based on the latest from here? Ok to close?

**Comment by safarmer** [comment]
> @safarmer Is #43 based on the latest from here? Ok to close?

That is correct. The commit from this PR is in #43

**Pull request closed without merging**
